login_views 작성 및 urls.py 작성
wecode-bootcamp-korea/27-westagram-backend-5-team pull request #13
Opened 2021-11-23 08:17 UTC by dbwls314

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 views.py 작성 및 엔드포인트 추가 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-23 08:26 UTC, se-yong reviewed
LGTM!~

2021-11-23 08:26 UTC, se-yong commented on students/youjin/westagram/users/views.py
> +            return JsonResponse({"message" : "KEY_ERROR"}, status=400)
LGTM!~

2021-11-23 08:52 UTC, yoohyeoni commented on students/youjin/westagram/users/views.py
> +            # 계정(이메일) 잘못 입력한 경우 or 비번 잘못 입력한 경우
주석 지우셔도 될거같아요!

2021-11-23 11:37 UTC, dbwls314 commented on students/youjin/westagram/users/views.py
> +            # 계정(이메일) 잘못 입력한 경우 or 비번 잘못 입력한 경우
감사합니다! 수정해보겠습니다!

2021-11-23 16:13 UTC, bigfanoftim requested changes

2021-11-23 16:13 UTC, bigfanoftim commented on students/youjin/westagram/users/urls.py
> +    path('/login', LoginView.as_view()),
`suggestion`과 같이 해당 `View`가 어떤 기능을 하는지 네이밍 또한 정확히, 엔드포인트 주소 또한 한 눈에 알아보기 쉽게 작성해주시면 좋을것 같아요~ `views.py`도 이와 같이 수정해주면 좋을 것 같습니다!
```suggestion
    path('/signup', SignUpView.as_view()),
    path('/login', LoginView.as_view()),
```

2021-11-24 04:56 UTC, dbwls314 commented on students/youjin/westagram/users/urls.py
> +    path('/login', LoginView.as_view()),
로그인뿐만 아니고, 회원가입 기능 관한 네이밍도 수정했습니다! 감사합니다~

2021-11-24 09:04 UTC, bigfanoftim requested changes

2021-11-24 09:04 UTC, bigfanoftim commented on students/youjin/westagram/westagram/urls.py
> +    path('singup', include('users.urls'))
`main urls.py`에서 `signup`으로 들어오는 모든 요청을 `users.urls`에 보내게 된다면 로그인 요청을 보낼 때에 주소는 `/signup/login`이 되는데 어색하지 않을까요?

2021-11-24 11:01 UTC, dbwls314 commented on students/youjin/westagram/westagram/urls.py
> +    path('singup', include('users.urls'))
그럼 main urls.py에서 지정해주는 pattern은 views.py에 작성하는 명칭들을 알 수 있는  naming 설정이 좋다는 말씀이신거죠?

2021-11-25 03:00 UTC, bigfanoftim commented on students/youjin/westagram/users/urls.py
> +    path('/login', LoginView.as_view()),
네 맞습니다! 하나의 View안에 post부터 get까지 정말 다양한 기능을 넣을 수 있겟지만, 그럴 경우 View 이름을 좀 더 포괄적인 단어로 표현하시면 되겠습니다!

2021-11-25 06:27 UTC, merged