[박세용] Mission 2: 모델링
wecode-bootcamp-korea/27-westagram-backend-5-team pull request #4
Opened 2021-11-18 09:08 UTC by se-yong

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-  Mission 2 모델링 / models.py 작성완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-18 09:42 UTC, bigfanoftim requested changes

2021-11-18 09:42 UTC, bigfanoftim commented on students/seyong/users/models.py
> +    gender = models.CharField(max_length=20, unique=True)
`gender`에 `unique=True` 속성을 주면 어떻게 작동될까 한번 생각해주세요!

2021-11-18 09:42 UTC, bigfanoftim commented on students/seyong/users/models.py
> +    gender = models.CharField(max_length=20, unique=True)
[Python Coding Convention](https://www.notion.so/wecode/wecode-Python-Coding-Convention-0a293f18b2244dfeb1005273d0a9dc75)
위 링크 참고하셔서 컨벤션 맞춰주세요!

2021-11-18 09:42 UTC, bigfanoftim commented on students/seyong/users/models.py
> +updated_at = models.DateTimeField(auto_now=True)
이 부분에 있어야 할 코드가 아닌 것 같습니다 PR 작성 전 다시 한번 본인 코드를 확인해주세요

2021-11-18 11:19 UTC, se-yong commented on students/seyong/users/models.py
> +    gender = models.CharField(max_length=20, unique=True)
> `gender`에 `unique=True` 속성을 주면 어떻게 작동될까 한번 생각해주세요!

다시한번 코드를 보고 생각해보니 gender 에는 중복 데이터가 충분히 있을수있으므로 삭제하는게 맞다고 느꼈습니다!
감사합니다.

2021-11-19 01:05 UTC, bigfanoftim commented
코드내에 클래스 단위로, 혹은 함수 단위로 = 을 기준으로 하여 코드를 정렬해주세요!
```suggestion
# BAD
point = models.DecimalField(max_digits=2, decimal_places=1)
user = models.ForeignKey('users.User', on_delete=models.CASCADE)
movie = models.ForeignKey('movie.Movie', on_delete=models.CASCADE)
created_at = models.DateField(auto_now_add=True)
updated_at = models.DateField(auto_now=True)

# GOOD
point      = models.DecimalField(max_digits=2, decimal_places=1)
user       = models.ForeignKey('users.User', on_delete=models.CASCADE)
movie      = models.ForeignKey('movie.Movie', on_delete=models.CASCADE)
created_at = models.DateField(auto_now_add=True)
updated_at = models.DateField(auto_now=True)
```

2021-11-19 06:12 UTC, merged