[유현이] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/27-westagram-backend-5-team pull request #7
Opened 2021-11-21 11:40 UTC by yoohyeoni

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-21 15:51 UTC, kyeongraekim requested changes
안녕하세요 현이님~ 아래 내용 확인해서 수정해주세요!

2021-11-21 15:51 UTC, kyeongraekim commented on students/hyeoni/users/views.py
> +
불필요한 공백이 많이 보이네요!~ 삭제해주세요~

2021-11-21 15:51 UTC, kyeongraekim commented on students/hyeoni/users/views.py
> +                return JsonResponse({"MESSAGE" : "PASSWORD_ERROR"}, status=400)
- 정규표현식을 사용할 경우, 자주 사용되는 경우가 아니라면 `compile()`해서 사용하지 않고, 
`match()`를 사용하는 것을 공식 문서에서 추천하고 있습니다.
compile 문을 쓰지 않은 코드 진행을 한 번 고민해주세요!~

- 전체적으로 각 코드 기능별 줄바꿈이 되어있지 않아 보이네요~ 적절한 곳에서 한칸의 줄바꿈 공백을 추가해주세요!

2021-11-22 06:04 UTC, bigfanoftim requested changes

2021-11-22 06:04 UTC, bigfanoftim commented on students/hyeoni/users/views.py
> +            user_phone_number   = data['phone_number']
`=` 정렬 부탁드립니다 현이님!!

2021-11-22 06:04 UTC, bigfanoftim commented on students/hyeoni/users/views.py
> +            if re.match('^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$', user_password) == None:
굳이 `None` 과 값을 비교할 필요가 없어 보입니다! `if not`으로 한번 바꿔보시겠어요?

2021-11-22 06:04 UTC, bigfanoftim commented on students/hyeoni/users/views.py
> +            if re.match('^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$', user_password) == None:
이 부분도 마찬가지입니다!

2021-11-22 06:05 UTC, bigfanoftim requested changes

2021-11-22 06:05 UTC, bigfanoftim commented on students/hyeoni/users/views.py
> +            if re.match('^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$', user_password) == None:
굳이 `None`과 비교할 필요가 없어 보입니다. `if not`으로 한번 바꿔보시겠어요?

2021-11-22 06:05 UTC, bigfanoftim commented on students/hyeoni/users/views.py
> +            if re.match('^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$', user_password) == None:
이 부분도 마찬가지입니다.

2021-11-22 06:07 UTC, bigfanoftim commented on students/hyeoni/users/views.py
> +            if re.match('^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$', user_password) == None:
그리고 두개의 정규표현식 모두 `user_password`와 비교하고 있는데 확인 부탁드려요

2021-11-22 09:26 UTC, merged