[이유진] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/27-westagram-backend-5-team pull request #9
Opened 2021-11-22 06:29 UTC by dbwls314

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- views.py에 회원가입시 필요한 정보, 중복확인 설정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-11-22 09:34 UTC, bigfanoftim requested changes

2021-11-22 09:34 UTC, bigfanoftim commented on students/youjin/westagram/users/views.py
> +        # users_password = re.compile()
불필요한 주석 삭제해주세요! 이전에 달렸던 리뷰 다시 한번 보시고 계속해서 모든 PR에 적용해주세요!

2021-11-22 09:34 UTC, bigfanoftim commented on students/youjin/westagram/users/views.py
> +        user_sns          = data['sns']
이 부분에서 발생되는 `KeyError`가 있을텐데 `try:` 안에 넣어서 예외 처리해주는게 좋아 보입니다!

2021-11-22 09:34 UTC, bigfanoftim commented on students/youjin/westagram/users/views.py
> +                return JsonResponse({"message": "KEY_ERROR"}, status=400)
파이썬에서는 if 조건문 평가시, 반환 되는 값 자체가 boolean 일 경우나, Truthy, Falsy 한 값일 경우,  == False == None == 0등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 not 을 활용해보세요 :)
```suggestion
            if not re.match('^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$', user_email):  
                return JsonResponse({"message": "KEY_ERROR"}, status=400)
            
            if not re.match('^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{8,}$', user_password):
                return JsonResponse({"message": "KEY_ERROR"}, status=400)

            if User.objects.filter(email=user_email).exists():
                return JsonResponse({"message" : "email_already_exists"}, status=400)                
```

2021-11-22 09:34 UTC, bigfanoftim commented on students/youjin/westagram/users/views.py
> +            return JsonResponse({"message": "ERROR"}, status=404)
어떤 에러가 나오던 다 이렇게 예외처리 해주시면 정확히 어디서 어떤 에러가 발생했는지 알 수 없기에 아래와 같이 처리해야합니다!
```suggestion
        except KeyError:
            return JsonResponse({"message": "key_error"}, status=400)
```

2021-11-22 13:14 UTC, dbwls314 commented on students/youjin/westagram/users/views.py
> +        user_sns          = data['sns']
-이메일 중복에 대한 예외 말고도, 핸드폰 번호도 중복이 될 수 없는데 핸드폰 번호는 중복에 대한 예외처리는 따로 필요없는걸까요?(1차 피트백 후 궁금중)

2021-11-23 01:37 UTC, bigfanoftim commented on students/youjin/westagram/users/views.py
> +                return JsonResponse({"message" : "이미 존재하는 이메일입니다. 이메일을 다시 입력해주세요."}, status=400)
에러 메세지는 실제 유저가 웹에서 볼 수 있는 에러가 아닙니다. api 서버에서 프론트엔드 개발자에게 보여줄 정보이기 때문에 너무 길게 작성할 필요가 없습니다.
```suggestion
                return JsonResponse({"message" : "email_already_exists"}, status=400)
```

2021-11-23 07:24 UTC, bigfanoftim requested changes

2021-11-23 07:24 UTC, bigfanoftim commented on students/youjin/westagram/users/views.py
> +            )
`users` 라는 변수에 생성된 객체를 담을 필요가 없어 보입니다!
```suggestion
            User.objects.create(
                name         = user_name,    
                email        = user_email,
                password     = user_password,
                phone_number = user_phone_number,
                gender       = user_gender,
                sns          = user_sns
            )
```

2021-11-23 07:46 UTC, merged